apiVersion: v1
kind: Service
metadata:
  name: {{ template "cp-kafka.fullname" . }}
  labels:
    app: {{ template "cp-kafka.name" . }}
    chart: {{ template "cp-kafka.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
spec:
  ports:
    - port: 9092
      name: broker
  selector:
    app: {{ template "cp-kafka.name" . }}
    release: {{ .Release.Name | quote }}