# Default values for cp-kafka-rest.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

## Image Info
## ref: https://hub.docker.com/r/confluentinc/cp-kafka/
image: confluentinc/cp-kafka-rest
imageTag: 4.1.0

## Specify a imagePullPolicy
## ref: http://kubernetes.io/docs/user-guide/images/#pre-pulling-images
imagePullPolicy: IfNotPresent

## Liveness and Readiness Probe Configuration
initialDelaySeconds: 60
timeoutSeconds: 10

servicePort: 8082

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

## External Access
## ref: https://kubernetes.io/docs/concepts/services-networking/service/#type-loadbalancer
external:
  enabled: false
  type: LoadBalancer

## If the Kafka Chart is disabled a URL and port are required to connect
cp-zookeeper:
  url: ""
  clientPort: 2181

## If the Kafka Chart is disabled a URL and port are required to connect
cp-schema-registry:
  url: ""
  port: 8081