apiVersion: apps/v1beta1
kind: StatefulSet

metadata:
  name: {{ template "cp-zookeeper.fullname" . }}
  labels:
    app: {{ template "cp-zookeeper.name" . }}
    chart: {{ template "cp-zookeeper.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
spec:
  serviceName: {{ template "cp-zookeeper.fullname" . }}-headless
  replicas: 3
  podManagementPolicy: Parallel
  template:
    metadata:
      labels:
        app: {{ template "cp-zookeeper.name" . }}
        release: {{ .Release.Name | quote }}
    spec:
      containers:
      - name: {{ template "cp-zookeeper.name" . }}-server
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        image: "{{ .Values.image }}:{{ .Values.imageTag }}"
        ports:
        - containerPort: {{ .Values.clientPort }}
          name: client
        - containerPort: {{ .Values.serverPort }}
          name: server
        - containerPort: {{ .Values.leaderElectionPort }}
          name: leader-election
        env:
        - name : ZK_TICK_TIME
          value: "{{ .Values.tickTimeMs }}"
        - name : ZK_SYNC_LIMIT
          value: "{{ .Values.syncTicks }}"
        - name: ZOOKEEPER_CLIENT_PORT
          value: "{{ .Values.clientPort }}"
        # SERVER_ID is required but not used as this value
        - name : ZOOKEEPER_SERVERS
          valueFrom:
            configMapKeyRef:
                name: {{ template "cp-zookeeper.fullname" . }}-configmap
                key: servers
        - name: ZOOKEEPER_SERVER_ID
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        command:
        - "bash"
        - "-c"
        - "ZOOKEEPER_SERVER_ID=$((${HOSTNAME##*-}+1)) && /etc/confluent/docker/run"
        volumeMounts:
        - name: datadir
          mountPath: /var/lib/zookeeper
          subPath: data
      {{ if not .Values.persistence.enabled }}
      volumes:
      - name: datadir
        emptyDir: {}
      {{- end }}
  {{- if .Values.persistence.enabled }}
  volumeClaimTemplates:
  - metadata:
      name: datadir
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: {{ .Values.persistence.size }}
      {{- if .Values.persistence.storageClass }}
      {{- if (eq "-" .Values.persistence.storageClass) }}
      storageClassName: ""
      {{- else }}
      storageClassName: "{{ .Values.persistence.storageClass }}"
      {{- end }}
      {{- end }}
  {{- end }}